### ISSUE TITLE
Update to latest egui and glfw

### ISSUE THREAD

**Issue by EriKWDev** [cohaereo/egui_glfw_gl#2]
Made an initial attempt in #1 , but wasn't quite able to get all the way. A lot has changed but I think I'm close.

See the following implementations for up-to-date backends:
- miniquad: https://github.com/not-fl3/egui-miniquad/blob/master/src/painter.rs
- glium: https://github.com/emilk/egui/blob/master/crates/egui_glium/src/painter.rs
- glow: https://github.com/emilk/egui/blob/master/crates/egui_glow/src/painter.rs

**Comment by cohaereo** [comment]
Resolved in #1
